brew "fish"
brew "git"
brew "mole"

cask "1password"
cask "1password-cli"
cask "aldente"
cask "betterdisplay"
cask "ghostty"
cask "kitlangton-hex"
cask "middleclick"
cask "raycast"
cask "spotify"
cask "tailscale-app"
cask "visual-studio-code"
